apiVersion: v1
data:
  mapRoles: "- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::768858414642:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-aQHwNZOViOFK\n
    \ username: system:node:{{EC2PrivateDNSName}}\n- groups:\n  - system:masters\n
    \ rolearn: arn:aws:iam::768858414642:role/UdacityFlaskDeployCBKubectlRole\n  username:
    build  \n"
kind: ConfigMap
metadata:
  creationTimestamp: "2024-10-05T11:13:28Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "5409"
  uid: cd910134-8298-4257-9ba5-4811ce5f0651